---
title: "aha exploration"
output: html_document
date: "2025-03-25"
---
```{r}
library(dplyr)
library(stringr)
```


```{r setup, include=FALSE}
test <- read_feather("/Users/loaner/Desktop/github-archive/haentity.feather")
```

```{r look at missing medicare nums}
missing_mcr <- test %>%
  filter(is.na(medicarenumber) & 
           (entity_type %in% c("Hospital"))) #, "Single Hospital Health System", #"IDS/RHA")))

mult <- missing_mcr %>%
  group_by(entity_uniqueid) %>%
  filter(n()>1) %>%
  ungroup()
```

```{r}
aha_data_dta <- aha_data_dta %>%
  mutate(lower = tolower(iconv(mname, from = "", to = "UTF-8", sub = "byte")))
```


```{r}
testing <- aha_data_dta %>%
  filter(str_detect(lower, regex("kindred", ignore_case = TRUE)))

testing2 <- missing_mcr %>%
  filter(str_detect(entity_name, regex("Christus", ignore_case = TRUE))) 

testing3 <- test %>%
  filter(entity_type == "Hospital") %>%
  filter(str_detect(entity_name, regex("Christus Spohn", ignore_case = TRUE))) %>%
  select(year, entity_uniqueid, entity_name, entity_type,medicarenumber,ahanumber, entity_address,entity_zip)
```

```{r}
missing_mcr <- missing_mcr %>%
  mutate(entity_zip_five = str_extract(entity_zip, "^\\d{5}"),
        hospname = str_to_lower(str_replace_all(entity_name, "[[:punct:]]", "")))

zip_lookup <- aha_data_dta %>%
  mutate(entity_zip_five = str_extract(mloczip, "^\\d{5}")) %>%
  group_by(ahanumber) %>%
  summarise(entity_zip_five = first(na.omit(entity_zip_five)), .groups = "drop")

# Step 2: Join back to original data
aha_mini <- aha_data_dta %>%
  left_join(zip_lookup, by = "ahanumber") %>%
  mutate(hospname = str_to_lower(str_replace_all(mname, "[[:punct:]]", "")),
         year = paste0(year),
         aha_entity_address = mlocaddr) %>% 
  select(hospname, mname, mcrnum, ahanumber, entity_zip_five, year, aha_entity_address)

merged <- missing_mcr %>%
    select(year, entity_uniqueid, entity_name, entity_type,medicarenumber,
           ahanumber, entity_address,entity_zip, entity_zip_five, hospname) %>%
  rename(himss_aha = ahanumber,
         mcloczip = entity_zip) %>%
  mutate(mname = entity_name) %>%
  left_join(aha_mini ,
            by = c('hospname', 'entity_zip_five')) #, 'year'))

still_missing <- merged %>%
  filter(is.na(ahanumber)) %>%

1- nrow(still_missing)/nrow(missing_mcr)

test <- still_missing %>%
  left_join(aha_mini %>% mutate(entity_address = aha_entity_address), 
            by = c('entity_zip_five', 'entity_address'))

still_missing2 <- test %>%
  filter(is.na(ahanumber.y))
1- nrow(still_missing2)/nrow(missing_mcr)

```

