name: proj-env
channels:
  - conda-forge
dependencies:
  - python=3.10.13
  - pandas==2.2.3
  - regex==2022.3.15
  - matplotlib==3.7.1
  - geopandas==1.0.1
  - networkx==3.1
  - tqdm==4.67.1
  - scipy=1.15.2
  - scikit-learn=1.3.2
  - numpy=1.24.4
  - requests==2.32.3
  - certifi=2025.4.26
  - geopy=2.4.1
  - pyarrow=21.0.0
  - seaborn
  - joblib
  - rapidfuzz
  - pip
  - pip:
    - jellyfish==1.2.0
    - Levenshtein 
    - metaphone 


